// Local dev-only stand-in for the real AI Services gateway — lets you test
// the Document A + Document B -> Document C compliance-document pipeline
// without needing the real AI_GATEWAY_KEY (which is a Vercel "Sensitive"
// env var and cannot be retrieved once set, by anyone).
//
// Run from hccs_backend-master (needs its node_modules for pdf-lib):
//   node scripts/mock-gateway.js
//
// Then, in .env.local for BOTH hccs-master and hccs_backend-master, set:
//   AI_GATEWAY_URL=http://localhost:4321
//   AI_GATEWAY_KEY=test-key-not-checked
//
// It returns a simple one-page PDF for any POST to /v1/compliance/pdf,
// standing in for "Document A" so you can verify the merge, storage upload,
// database row, and admin-panel display all work end to end. Never used in
// production — nothing in the app references this file.

const http = require("http");
const { PDFDocument, StandardFonts } = require("pdf-lib");

const PORT = 4321;

async function buildPlaceholderPdf(body) {
    const doc = await PDFDocument.create();
    const page = doc.addPage([595, 842]);
    const font = await doc.embedFont(StandardFonts.Helvetica);
    const scanData = body?.scanData || {};
    const summary = body?.summary || {};

    const lines = [
        "TEST PLACEHOLDER — NOT A REAL COMPLIANCE REPORT",
        "",
        `Company: ${scanData.company_name || "-"}`,
        `Contact: ${scanData.contact_name || "-"}`,
        `Total score: ${summary.totalScore ?? "-"}`,
        `Risk level: ${summary.riskLevel ?? "-"}`,
        "",
        "Generated by the local mock gateway (scripts/mock-gateway.js) for",
        "testing the Document A / B / C combining feature — this is not the",
        "real AI-rendered report.",
    ];

    let y = 780;
    for (const line of lines) {
        page.drawText(line, { x: 50, y, size: 12, font });
        y -= 20;
    }

    return doc.save();
}

const server = http.createServer((req, res) => {
    if (req.method === "POST" && req.url === "/v1/compliance/pdf") {
        let chunks = [];
        req.on("data", (c) => chunks.push(c));
        req.on("end", async () => {
            let body = {};
            try {
                body = JSON.parse(Buffer.concat(chunks).toString("utf8"));
            } catch {
                // ignore parse errors, use empty body
            }
            const bytes = await buildPlaceholderPdf(body);
            res.writeHead(200, { "Content-Type": "application/pdf" });
            res.end(Buffer.from(bytes));
        });
        return;
    }
    res.writeHead(404);
    res.end("not found");
});

server.listen(PORT, () => {
    console.log(`Mock AI gateway listening on http://localhost:${PORT}`);
    console.log("POST /v1/compliance/pdf returns a placeholder PDF.");
});
